export const SEUIL_DEFAULTS: Record<string, number> = {
  tauxMargeNette: 38,
  tauxDemarque: 3,
  stockAge: 30,
  gmroi: 3.84,
  delaiTel: 30, delaiConsole: 30, delaiJV: 30, delaiTablette: 30, delaiPC: 30,
  tauxTransformation: 40,
  estalyParSemaine: 5,
  noteGoogle: 4.4,
  poidsDigital: 15,
  tauxAnnulationWeb: 20,
  tauxSAV: 5,
  gammeTel: 37,
  gammeJV: 19,
  tauxAchatExterne: 15,
  tauxPiceasoft: 70,
  masseSalarialePct: 15,
  tauxTurnover: 20,
  tauxFormation: 80,
  panierMoyen: 50,
};
